Debug buttons
micahstairs/bga-innovation pull request #80
Opened 2021-11-01 02:26 UTC by normaljosh

For issue #35 , to add debug buttons. 

The "return this card" button doesn't do anything yet and I haven't really had the chance to test much, but this is where I'm at so far.

2021-11-01 16:58 UTC, micahstairs commented
So it seems that this pull request contains a lot more changes than you intended! It looks like you branched off of `main-new-graphics` since I see a lot of graphic refresh changes in here. I also suspect that you tried renaming files manually instead of using the PHP rename script (since there are comments within the file that still say "InnovationNormalJosh" in it).

Did you try following the flow I documented in https://github.com/micahstairs/bga-innovation#readme? It will likely be easiest to create a new branch and copy in the couple pieces of code that you intended to change, and create a new pull request with that new branch. Feel free to message me on discord if you are having trouble with any of these steps!

2021-11-01 17:11 UTC, normaljosh commented
I was afraid of that! I did use the php rename script, but I didn't validate or really look at the merge because I was late. 

The code was originally cloned using the  "overwrite" button in bga studio, so it must've grabbed main-new-graphics at some point. I can do it again following your workflow for sure, just might be a couple days to get the right bits merged in (ended up touching a lot of the code related to moving cards to achievements)

2021-11-01 17:51 UTC, micahstairs commented
Ah yeah, cloning using that overwrite feature won't work well in this case, since it grabs a snapshot of whatever I happen to have pushed to the project at the time (and git won't know how to properly coordinate that with our commit history and branches).

Take your time! This will definitely be useful when it's ready, but it's not blocking me from making progress. Once you get this flow figured out for the first time, it will become a lot easier in the future!

2021-11-02 10:35 UTC, micahstairs commented
Oh one more thing @normaljosh! Can you make these changes off of `main-artifacts` instead of `main`? I think that would be better since your changes affect some of the logic around achievements and we don't want to accidentally break the real version of the game. Also, this would eliminate messy merge conflicts since I also touched some of the achievement logic (this may actually reduce the amount of code that you have to touch).

2021-11-02 20:39 UTC, normaljosh commented
Alright, think I did it right this time! Changed the base branch to main-artifacts as well. I still need to make "return this card" functional.

2021-11-03 14:26 UTC, micahstairs requested changes
Thanks for this work! Left some comments on the wordings.

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +            $message_for_others = clienttranslate('${player_name} draws and achieves ${<}${age}${>} ${<<}${name}${>>}.');
If someone draws and achieves, then they shouldn't see the name of the card.

${player_name} draws and achieves a ${<}${age}${>}.

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +            $message_for_others = clienttranslate('${player_name} achieves ${<}${age}${>} ${<<}${name}${>>} from his hand.');
${player_name} achieves a ${<}${age}${>} from his hand.

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +            break;
${player_name} achieves a ${<}${age}${>} from his score pile.

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +                $message_for_player = clienttranslate('{You must} reveal {number} {card} from your hand');
achieve

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +                $message_for_others = clienttranslate('{player must} reveal {number} {card} from his hand');
achieve

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +                $message_for_others = clienttranslate('{player must} tranachievesfer {number} {card} from his score pile');
This is a creative word, but let's stick with "achieve" haha

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +                $message_for_opponent = clienttranslate('${player_name} transfers ${<}${age}${>} ${<<}${name}${>>} from his hand to ${your} achievements.');
${player_name} transfers a ${<}${age}${>} from his hand to ${your} achievements.

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +                $message_for_opponent = clienttranslate('${player_name} transfers ${<}${age}${>} ${<<}${name}${>>} from his hand to ${your} achievements.');
Even though it is going to their achievements, they aren't supposed to look at it.

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +                $message_for_others = clienttranslate('${player_name} transfers a ${<}${age}${>} from his board to ${opponent_name}\'s achievements.');
${<}${age}${>} ${<<}${name}${>>}

It's fine the say the name of the card here since the card came from a visible location.

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +                $message_for_opponent = clienttranslate('${player_name} transfers ${<}${age}${>} ${<<}${name}${>>} from his score pile to ${your} achievements.');
{player_name} transfers a ${<}${age}${>} from his score pile to ${your} achievements.

2021-11-03 14:26 UTC, micahstairs commented on innovation.game.php
> +                $message_for_player = clienttranslate('${You} transfer ${<}${age}${>} ${<<}${name}${>>} from ${opponent_name}\'s hand to your achievements.');
${You} transfer a ${<}${age}${>} from ${opponent_name}\'s hand to your achievements.

2021-11-04 11:44 UTC, normaljosh commented
Thanks for the catches, I forgot about the visibility of cards when achieving. Changes have been made!

2021-11-04 13:45 UTC, micahstairs requested changes
A few minor fixes left!

2021-11-04 13:45 UTC, micahstairs commented on innovation.game.php
> +                $message_for_opp onent = clienttranslate('${player_name} transfers a ${<}${age}${>} from his achievements to ${your} achievements.');
You accidentally added a space here which will break the game since this is no longer valid PHP syntax.

2021-11-04 13:45 UTC, micahstairs commented on innovation.game.php
> +                // self::trace('playerTurn->justBeforeGameEnd');
Please remove this commented out line

2021-11-04 13:45 UTC, micahstairs commented on innovation.game.php
> +                self::trace('EOG bubbled from self::achieve');
This should be:

self::trace('EOG bubbled from self::debug_achieve');

2021-11-04 13:45 UTC, micahstairs commented on innovation.game.php
> +                $message_for_others = clienttranslate('${player_name} transfers  ${<}${age}${>} ${<<}${name}${>>} from his board to ${opponent_name}\'s achievements.');
Please remove this extra space

2021-11-04 13:45 UTC, micahstairs commented on innovation.game.php
> +                break
You accidentally removed the ; which will make this code unable to run.

2021-11-05 12:22 UTC, normaljosh commented
Thanks for the patience, fixed em! I just added the PHP Intelephense extension for vscode to help me catch when I break PHP syntax.

2021-11-05 17:15 UTC, micahstairs requested changes

2021-11-05 17:15 UTC, micahstairs commented on innovation.game.php
> +                self::trace('EOG bubbled from self::achieve');
Please update `self::trace('EOG bubbled from self::achieve');` to `self::trace('EOG bubbled from self::debug_achieve');`.

2021-11-06 07:53 UTC, micahstairs approved these changes
Thanks!

2021-11-06 07:53 UTC, merged